login/routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
//Route homepage
Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index');

Route::get('/homepage', function () {
    return view('homepage');
});

Route::get('/loginpage', function () {
    return view('loginpage');
});

//Route Đăng nhập
Route::get('/registed', 'HomeController@registed');

Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

Auth::routes();


//Route booking
Route::resource('cars', 'BookingController');

Route::resource('orders', 'OrderController');

Route::get('/history','OrderController@history');

login/app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
	protected $table = 'cars';
    //
    protected $fillable = [
    	'id',
    	'brand',
    	'nos',
    	'color',
    	'type',
    	'status',
        'user_id',
    ];
}

login/app/Models/SocialProvider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SocialProvider extends Model
{
	protected $fillable = ['provider_id','provider'];
    //

    function user()
    {
        return $this->belongsTo(User::class);
    }

}

login/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    function socialProviders()
    {
        return $this->hasMany(SocialProvider::class);
    }
}

login/app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
    protected $table = 'orders';
    //
    protected $fillable = [
    	'id',
    	'car_id',
        'user_id',
    	'brand',
    	'name',
    	'phone_number',
    	'email',
    ];

    public $timestamps = false;
}

login/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    function socialProviders()
    {
        return $this->hasMany(SocialProvider::class);
    }
}

login/app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Car;


class BookingController extends Controller
{
    //
    public function index()
    {
        //
        $cars = Car::all();
        
        return view('cars.index', array('cars' => $cars));
        
    }

    public function show($id)
    {
        // dd($id);
        $car = Car::find($id);

        return view('cars.show', array('car' => $car));
    }

    

}

login/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

login/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }

    public function registed(){
        return view('registed');
    }
}

login/app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;

class OrderController extends Controller
{
    //
    public function store(Request $request){
        // dd($request->txtId);
        $order = new Order;
        $order->car_id = $request->txtId;
        $order->brand = $request->txtBrand;
        $order->name = $request->txtName;
        $order->phone_number = $request->txtPhoneNumber;
        $order->email = $request->txtEmail;
        $order->user_id = $request->txtUserId;
        $order->save();
        return view('/homepage');
    }

    public function index()
    {
        //
        $orders = Order::all();
        return view('orders.index', array('orders' => $orders));
        
    }

    public function history()
    {
        //
        $orders = Order::all();
        return view('/history', array('orders' => $orders));
    }


}

login/resources/views/cardetail.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Vehicle in your hand</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <!-- Styles -->
        <!-- <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style> -->
        <style>
            html {
                box-sizing: border-box;
            }
            *,
            *::before,
            *::after {
                box-sizing: inherit;
            }
            .button {
                padding: 10px 5px;
                background-color: green;
                color: #fff;
            }
            .form {
                border: 1px solid #ccc;
                background-color: #f9f9f9;
                display: block;
                width: 400px;
                height: 150px;
                text-align: center;
                margin: 20px auto 0 auto;
                display: none;
            }
        </style>
        <center><h2 class="title m-b-md">
            Car information detail
        </h2></center>
    </head>
    <body>
         <center>
         <table border="2">
             <tr>
                <td>Hãng xe: </td>
                <td>   </td>
             </tr>
             <tr>
                <td>Số chỗ: </td>
                <td>   </td>                          
             </tr>
             <tr>
                <td>Màu sắc: </td>
                <td>   </td> 
             </tr>
             <tr>
                <td>Loại xe(tự lái hay có người lái): </td>
                <td>   </td>
             </tr>
         </table>
         <button class="button" type="button" id="btnBooking">Đặt xe</button>
         <button class="button" type="button">Quay trở lại</button>
         </center>
        <div class="form" id="detailForm">
            <form action="" style="height: 150px; width: 300px;">
                <center>
                <tr>
                    <td>Họ và Tên</td>
                    <td><input type="text" name="txtName"/></td>
                </tr>
                <tr>
                    <td>Số điện thoại</td>
                    <td><input type="text" name="txtPhoneNumber"/></td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td><input type="text" name="txtEmail"/></td>
                </tr>
                <button type="button" class="button" style="margin: 0 auto;">Book</button>
                </center>
            </form>
        </div>
        <script>
             $("#btnBooking").click(function(){
                $("#detailForm").show();
            });
        </script>

    </body>
</html>

login/resources/views/cars/index.blade.php
@extends('layouts.app')

@section('content')
<head>
    <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 30px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
</head>
<body>
    <center>
    <div class="title m-b-md">
            Bấm để xem thông tin chi tiết về xe
    </div>    
        <table class="table table-bordered" border="2">
        <thead>
                <th>Mã</th>
                <th>Tên</th>
                <th>Trạng thái</th>
                <th>Màu sắc</th>
                <th></th>
        </thead>

        @foreach ($cars as $car)
            
            <tbody>
                <tr>
                    <td>{{ $car->id }}</td>
                    <td>{{ $car->brand }}</td>
                    <td>{{ $car->status }}</td>
                    <td>{{ $car->color }}</td>
                    <td><a href="http://localhost:8000/cars/{{ $car->id }}">Chi tiết</a></td>
                </tr>
            </tbody>
        @endforeach
        </table>
<body>
@endsection

login/resources/views/cars/show.blade.php
@extends('layouts.app')

@section('content')
<head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 40px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
            .form {
                border: 5;
                background-color: #f9f9f9;
                display: block;
                width: 200px;
                height: 120px;
                text-align: center;
                margin: 20px auto 0 auto;
                display: none;
            }            
        </style>
</head>
<body>
        <center>
            <div class="title m-b-md">
                    Thông số chi tiết về xe {{ $car->brand }}
            </div>    
                 <table>
                     <tr>
                        <td>Hãng xe: </td>
                        <td>{{ $car->brand }}</td>
                     </tr>
                     <tr>
                        <td>Số chỗ: </td>
                        <td>{{ $car->nos }}</td>                          
                     </tr>
                     <tr>
                        <td>Màu sắc: </td>
                        <td>{{ $car->color }}</td> 
                     </tr>
                     <tr>
                        <td>Loại xe(tự lái hay có người lái): </td>
                        <td>{{ $car->type }}</td>
                     </tr>
                     <tr>
                        <td>Trạng thái: </td>
                        <td>{{ $car->status }}</td>
                     </tr>
                 </table>
                 <button type="button" class="btn btn-default" id="btnBooking1">Đặt xe ngay</button>
                 <button class="btn btn-default" onclick="window.location.href='/cars'">Quay trở lại</button>
        </center>
        <center>
                <div class="form" id="detailForm">
                    <form method="POST" action="{!! route('orders.store') !!}" name="frmAdd">
                        <div class="form-group">
                        <input type="hidden" name="_token" value="{!! csrf_token() !!}" />
                        </div>
                        <div class="form-group">
                        <input type="text" name="txtName" class="form-control" placeholder="Họ và tên..." style="width: 200px;" value="{{ Auth::user()->name }}" />
                        </div>
                        <div class="form-group">
                        <input type="text" name="txtPhoneNumber" class="form-control" placeholder="Số điện thoại..." style="width: 200px;"/>
                        </div>
                        <div class="form-group">
                        <input type="text" name="txtEmail" class="form-control" placeholder="Email..." style="width: 200px;" value="{{ Auth::user()->email }}"/>
                        </div>
                        </br>
                        <input type="hidden" name="txtId" class="form-control" value="{{ $car->id }}"/>
                        <input type="hidden" name="txtBrand" class="form-control" value="{{ $car->brand }}"/>
                        <input type="hidden" name="txtUserId" class="form-control" value="{{ $car->user_id }}"/>
                        <button type="submit" class="btn btn-default">Đặt xe</button>
                    </form>
                </div>
        </center>
        <script>
             $("#btnBooking1").click(function(){
                $("#detailForm").show();
            });
        </script>
<body>
@endsection

login/resources/views/history.blade.php
@extends('layouts.app')

@section('content')
<head>
    <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 30px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
</head>
<body>
    <center>
    <div class="title m-b-md">
            Lịch sử những lần đặt xe
    </div>    
        <table class="table table-bordered" border="2">
        <thead>
                <th>Id của xe</th>
                <th>Tên xe</th>
                <th>Tên người đặt</th>
                <th>Số điện thoại</th>
                <th>Email</th>
        </thead>
        @foreach ($orders as $order)
            @if((Auth::user()->email) == ($order->email))         
                    <tbody>
                        <tr>
                            <td>{{ $order->car_id }}</td>
                            <td>{{ $order->brand }}</td>
                            <td>{{ $order->name }}</td>
                            <td>{{ $order->phone_number }}</td>
                            <td>{{ $order->email }}</td>
                            <td><a href="">Xóa</a></td>
                        </tr>
                    </tbody>
            @endif
        @endforeach
        </table>
<body>
@endsection

login/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Thông báo</div>

                <div class="panel-body">
                    <a href='http://localhost:8000/homepage'>Đăng nhập thành công, bấm để quay lại trang chủ' </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

login/resources/views/homepage.blade.php
@extends('layouts.app')

@section('content')
<head>
    <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 50px;
            }

            .links > a {
                color: #636bf;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
</head>
<body>
    <center>
        <div>
            <div class="content">
                <div class="title m-b-md">
                    Welcome to Vehicle in your hand<br>
                    Have a good day !!!
                </div>
            </div>
        </div>
    <div class="title m-b-md">
        <div class="links">
            <a href="http://localhost:8000/cars">Bấm để xem danh sách các xe</a>
        </div>
    </div>
    </center>
<body>
@endsection

login/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        <!-- {{ config('app.name', 'Laravel') }} -->
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/auth/facebook') }}">Login with facebook</a></li>
                            <li><a href="{{ url('/auth/google') }}">Login with google account</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                    <a href="">
                                    Quản lý tài khoản
                                    </a>
                                    </li>
                                    <li>
                                    <a href="{!! route('orders.index') !!}">
                                    Quản lý các đơn đặt xe
                                    </a>
                                    </li>
                                    <li>
                                    <a href="{{ url('/history') }}">
                                    Lịch sử
                                    </a>
                                    </li>
                                    @if (Auth::user()->password != "")                                    
                                        <li>
                                        <a href="">
                                        Đổi mật khẩu
                                        </a>
                                        </li>
                                    @endif                                    
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Đăng xuất
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

login/resources/views/loginpage.blade.php
<!DOCTYPE html>
<html lang="en"><head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="css/normalize.css">
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link href="/css/app.css" rel="stylesheet">
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  </style>
  <!-- Scripts -->
  <script>
      window.Laravel = <?php echo json_encode([
          'csrfToken' => csrf_token(),
      ]); ?>
  </script>
</head>
<body>
   <div class="container">
    <div class="omb_login">
        <h3 class="omb_authTitle">Đăng nhập hoặc <a href="{{ url('/register') }}">Đăng kí</a></h3>
        <div class="row omb_row-sm-offset-3 omb_socialButtons">
            <div class="col-xs-4 col-sm-2">
                <a href="{{ url('/auth/facebook') }}" class="btn btn-lg btn-block omb_btn-facebook">
                    <i class="fa fa-facebook visible-xs"></i>
                    <span class="hidden-xs">Facebook</span>
                </a>
            </div>
            <div class="col-xs-4 col-sm-2">
                <a href="#" class=>
                </a>
            </div>  
            <div class="col-xs-4 col-sm-2">
                <a href="{{ url('/auth/google') }}" class="btn btn-lg btn-block omb_btn-google">
                    <i class="fa fa-google-plus visible-xs"></i>
                    <span class="hidden-xs">Google+</span>
                </a>
            </div>  
        </div>

        <div class="row omb_row-sm-offset-3 omb_loginOr">
            <div class="col-xs-12 col-sm-6">
                <hr class="omb_hrOr">
                <span class="omb_spanOr">or</span>
            </div>
        </div>

        <div class="row omb_row-sm-offset-3">
            <div class="col-xs-12 col-sm-6">    
                <form class="omb_loginForm" action="" autocomplete="off" method="POST">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        <input type="text" class="form-control" name="username" placeholder="Tên đăng nhập">
                    </div>
                    <span class="help-block"></span>
                                        
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        <input  type="password" class="form-control" name="password" placeholder="Mật khẩu">
                    </div>
                    <span class="help-block"></span>

                    <button class="btn btn-lg btn-primary btn-block" type="submit">Đăng nhập</button>
                </form>
            </div>
        </div>
        <div class="row omb_row-sm-offset-3">
            <div class="col-xs-12 col-sm-3">
                <label class="checkbox">
                    <input type="checkbox" value="remember-me">Ghi nhớ
                </label>
            </div>
            <div class="col-xs-12 col-sm-3">
                <p class="omb_forgotPwd">
                    <a href="#">Quên mật khẩu?</a>
                </p>
            </div>
        </div>          
    </div>



        </div>
</body>
</html>
    

login/resources/views/registed.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Thông báo</div>

                <div class="panel-body">
                    <a href='http://localhost:8000/homepage'>Đăng ký thành công</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection